export const CHECK_TOKEN = 'CHECK_TOKEN';
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const KEY_EXCHANGE_REQUEST = "KEY_EXCHANGE_REQUEST";
export const KEY_EXCHANGE_SUCCESS = "KEY_EXCHANGE_SUCCESS";
export const KEY_EXCHANGE_FAILURE = "KEY_EXCHANGE_FAILURE";
export const GET_LOGIN_URL_REQUEST = "GET_LOGIN_URL_REQUEST";
export const GET_LOGIN_URL_SUCCESS = "GET_LOGIN_URL_SUCCESS";
export const GET_LOGIN_URL_FAILURE = "GET_LOGIN_URL_FAILURE";

export const GET_LOGOUT_URL_REQUEST = "GET_LOGOUT_URL_REQUEST";
export const GET_LOGOUT_URL_SUCCESS = "GET_LOGOUT_URL_SUCCESS";
export const GET_LOGOUT_URL_FAILURE = "GET_LOGOUT_URL_FAILURE";

export const GO_HOME = "GO_HOME";


export const SUPPLIERS_REQUEST = "SUPPLIERS_REQUEST";
export const SUPPLIERS_SUCCESS = "SUPPLIERS_SUCCESS";
export const SUPPLIERS_FAILURE = "SUPPLIERS_FAILURE";

export const SET_REPORTS_PARAMS = "SET_REPORTS_PARAMS";

export const GET_REPORT_REQUEST = 'GET_REPORT_REQUEST';
export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
export const GET_REPORT_ERROR = 'GET_REPORT_ERROR';
export const SET_SUPPLIER = 'SET_SUPPLIER'; //This is for use by external users.
export const SET_SUPPLIER_ID = 'SET_SUPPLIER_ID'; //This is for use by employees
export const EMPLOYEE_GO_SUPPLIER = "EMPLOYEE_GO_SUPPLIER";

export const SINGLE_SUPPLIER_REQUEST = "SINGLE_SUPPLIER_REQUEST";
export const SINGLE_SUPPLIER_SUCCESS = "SINGLE_SUPPLIER_SUCCESS";
export const SINGLE_SUPPLIER_FAILURE = "SINGLE_SUPPLIER_FAILURE";
export const SINGLE_SUPPLIER_CLEAR = "SINGLE_SUPPLIER_CLEAR";

export const GET_CONTENT_REQUEST = "GET_CONTENT_REQUEST";
export const GET_CONTENT_SUCCESS = "GET_CONTENT_SUCCESS";
export const GET_CONTENT_ERROR = "GET_CONTENT_ERROR";
